- .github/CODEOWNERS
- .github/FUNDING.yml
- .gitignore
- src/lib/constants/schemas.ts
- src/lib/env.ts
- src/modules/core/listeners/member-add.ts
- src/modules/ticket/listeners/member-leave.ts
[Added new feature, give role to new users on discord server log](https://github.com/pedromondek/lacoste/commit/80672cfb53155e02e6fe04e43231adbb631e6235)
[Added new validation for memberLeave](https://github.com/pedromondek/lacoste/commit/596a4b6d1602b5640e63d7ec99f957ad3783926c)
> Feature auto add role discord

- src/modules/core/listeners/member-add.ts
Fix: Auto role now works with sector roles.
> Auto role works with sector roles and cargo.

- src/lib/constants/imgs-thumbnail.ts
- src/modules/core/commands/send.ts
File with links to images used in
> Modify send archive

- src/modules/core/listeners/member-add.ts
- src/modules/ticket/interactions/downgrade.ts
- src/modules/ticket/interactions/fire.ts
- src/modules/ticket/interactions/hire.ts
- src/modules/ticket/listeners/member-leave.ts
- src/modules/work/interactions/promotion.ts
- New method updateDiscordLogRole that auto-synchronizes roles from the main server to the script and log server.
- Type correction (removal of any, as const), using the appropriate types.
- Consumption of the updateDiscordLogRole method in the functions: "Promotion", "Downgrade", "Hire", "Fire", "Member Leave".
> Auto sync roles log server

- src/modules/core/commands/verify.ts
- Fixed an error where when searching for the user's name with a special character in the "-verificar" command, the search in the database ends up considering it as part of a query.
> Search username on database fixed for all username types

- src/modules/work/interactions/department.ts
- Checks for users who are away, if there is 1 day left of renewal, they are notified about it.
- Checks for users who are away, if the renewal has ended, the new function is called to automatically return them and notify them.
- New function autoReturn, automatically returns the user from the renew.
> Applies auto return to user with activeRenewal

- src/modules/core/interactions/changeDiscordAccount.ts
The changeDiscordAccount function now calls switchAccountDiscordLogRole on the log server to switch roles between Discord accounts.
> Auto sync role with changeDiscordAccount on Log Server

- src/lib/utilities/discord.ts
- src/modules/core/commands/verify.ts
- src/modules/work/interactions/promotion.ts
The user's position when checking if a promotion is possible does not change the final result of 'isPromotionPossible', fixed.
> Fix Verify (isPromotionPossible)

- src/modules/core/commands/link.ts
- src/modules/core/commands/verify.ts
- src/modules/form/interactions/acompanhamento.ts
- src/modules/form/interactions/acompanhamentoAdm.ts
- src/modules/form/interactions/avaliativo.ts
- src/modules/form/interactions/entrevista.ts
- src/modules/form/interactions/reclamação.ts
- src/modules/form/interactions/sugestões.ts
- src/modules/ticket/interactions/fire.ts
- src/modules/ticket/interactions/hire.ts
- src/modules/ticket/interactions/notes.ts
- src/modules/ticket/interactions/warns.ts
- One more check for Habbo Interaction
> Fix Interaction Name Display

- src/modules/core/commands/send.ts
- src/modules/core/interactions/updatePresences.ts
- [Extended permission for Lider Organizacional](https://github.com/cauemondek/lacoste/commit/fdfebd2c6e57de133f655b4113ee4bd5e620b337)
> Extended permissions update presences

- src/modules/core/commands/link.ts
- src/modules/work/interactions/department.ts
Transformado o comando link em slash-command, alterado algumas respostas visuais
> link_slash_command

- src/modules/core/commands/link.ts
- src/modules/form/interactions/organizacional.ts
- Changed time for schedule and form presence daily;
- Change text for link response.
> Change time form presence

- src/modules/core/commands/verify.ts
- Added one more line to form 'Verificar': last presence.
> New verification for last presence

- package.json
- src/lib/utilities/discord.ts
- src/modules/core/commands/pingDiscord.ts
- src/modules/core/commands/verify.ts
- src/modules/form/interactions/organizacional.ts
- Add Moment;
- Modified the way time until promotion is calculated;
- isNotSelfPromotion considers the interaction that was used;
> Verify change embed time and organizacional dates

- src/lib/utilities/discord.ts
- src/modules/core/commands/link.ts
- New function to verify if user is a bot;
- Don't allow link bots.
> Don't link bots

- src/modules/core/commands/verify.ts
- Fix shouldPromote now check timeForPromote
> Fix shouldPromote

- src/modules/core/interactions/updatePresences.ts
- updates CG and Total presence separately
- change required field on update presence form
> Update Presences Changes

- prisma/schema.prisma
- src/lib/utilities/discord.ts
- src/modules/core/interactions/updateApprovedSuggestions.ts
- src/modules/core/interactions/updatePresences.ts
Foi adicionado tema e titulo a suggestions além de fazer pequenas melhorias.
> Adicionado Titulo e Tema em Sugestões

- src/modules/core/interactions/createMedal.ts
- src/modules/core/interactions/deleteMedal.ts
- Correção de visualização de medalhas em caso de remoção, paginado
- Barramento de novo formulario caso já tenha um aberto, esperando fechamento automatico
> fix-show-medals-functions

- src/modules/core/interactions/updateApprovedSuggestions.ts
Corrigido o bug ao tentar criar sugestão o tempo restante ficava negativo para reutilizar o comando
> Bug Fix Create Suggestions

- src/modules/ticket/interactions/hire.ts
Agora ao tentar contratar um estagiário, é negado e guiado para a forma correta
> Negação da contratação de Estagiário
